name: Sakchhi Srivastava, Data Enthusiast
markdown: kramdown
title: Sakchhi's Blog
description: My Awesome Blog about Machine Learning

permalink: /blog/:year/:month/:day/:title


theme: jekyll-theme-midnight
